export const productList = [
    {
        id: 1, type1: true, type2: false, type3: false,
        nameKor: '룰루셀 화이트닝 콤플렉스 앰플', nameEng: 'Lulucell Whitening Complex Ampoule',
        thumb: '/product/product-img-whitening_complex_ampoule.jpg',
        detail: ['/product/detail-whitening_complex_ampoule.jpg'],
        size: '50ml',
        desc: '나이아신아마이드(비타민B3), 글루타치온, 비타민나무열매추출물이 함유되어 잡티 없이 맑고 어린 피부로 만들어주는 화이트닝 콤플렉스앰플입니다.',
        tag: ['#미백','#톤업','#항노화'],
        ingredient: '나이아신아마이드, 비타민나무열매추출물, 글루타치온',
    },
    {
        id: 2, type1: false, type2: false, type3: true,
        nameKor: '룰루셀 브라이트닝 유브이 쉴드 선스크린', nameEng: 'Lulucell Brightening UV Shield Sunscreen',
        thumb: '/product/product-img-brightening_uv_shield_sunscreen.jpg',
        detail: ['/product/detail-brightening_uv_shield_sunscreen.jpg'],
        size: '50ml',
        desc: '백탁 현상과 끈적임이 없는 촉촉하고 발림성이 좋은 혼합 자차 선스크린입니다.',
        tag: ['#혼합 자차','#수분','#피부활력'],
        ingredient: '호모살레이트, 에칠헥실살리실레이트, 티타늄디옥사이드, 초저분자 히알룰론산',
    },
    {
        id: 3, type1: true, type2: false, type3: false,
        nameKor: '룰루셀 울트라 리페어', nameEng: 'Lulucell Ultra Repair',
        thumb: '/product/product-img-ultra_repair.jpg',
        detail: ['/product/detail-ultra_repair.jpg'],
        size: '5ml',
        desc: '염증 완화에 탁월한 감초추출물과 나이아신아미드 및 복합 펩타이드 함유로 피부재생과 피부 개선에 특화된 스킨부스터입니다.',
        tag: ['#피부재생', '#항염증', '#항산화'],
        ingredient: '펩타이드, 감초추출물, 나이아신아마이드',
    },
    {
        id: 4, type1: true, type2: false, type3: false,
        nameKor: '룰루셀 울트라 디엔에이', nameEng: 'Lulucell Ultra DNA',
        thumb: '/product/product-img-ultra_dna.jpg',
        detail: ['/product/detail-ultra_dna.jpg'],
        size: '5ml',
        desc: 'PDRN(연어의 정액에서 추출된 DNA)과 필수 아미노산인 류신, 이소류신, 발린, 라이신, 트레오닌 성분이  피부콜라겐 생성을 촉진하여 주름없이 매끈하고 쫀쫀한 피부를 만들어 주는 안티에이징 스킨부스터입니다.',
        tag: ['#피부재생', '#콜라겐 생성', '#주름개선', '#피부탄력'],
        ingredient: '폴리데옥시리보뉴클리오티드, 류신, 이소류신, 발린, 라이신, 트레오닌',
    },
]